#!/bin/bash
#
# tomcat Control script for tomcat 7       
#
# chkconfig: 2345 20 80
# description: 	Start up the Tomcat servlet engine.

# Source function library.
. /etc/init.d/functions


RETVAL=$?
CATALINA_HOME="/opt/tomcat7"
CATALINA_PID=/var/run/tomcat/tomcat7.pid

NAME=`basename $0`

start() {
	if [ -f $CATALINA_HOME/bin/startup.sh ]; then
    	echo $"Starting Tomcat"
    	if [ ! -e /var/run/tomcat ]; then
    		mkdir -p /var/run/tomcat
    		chown tomcat /var/run/tomcat
    	fi
        /bin/su tomcat $CATALINA_HOME/bin/startup.sh
        if [ $? -eq 0 ]; then
        	success "Tomcat started."
        else
        	failure "Tomcat failed to start"
        	RETVAL=$?
        fi
    fi
}

stop() {
	if [ -f $CATALINA_PID ]; then
		echo $"Stopping Tomcat"
	    kill `cat $CATALINA_PID`
	    rm -rf $CATALINA_PID
	    success "Tomcat stopped."
	fi
}

case "$1" in
 	start)
       start
	;;
 	stop)
       stop
 	;;
 	restart)
        stop
        sleep 10
        start
        ;;
	status)
	    status -p $CATALINA_PID $NAME
	    RETVAL=$?   
	    ;;
	 *)
        echo $"Usage: $0 {start|stop|restart|status}"
		exit 1
		;;
esac

exit $RETVAL