CREATE ROLE oaiserver LOGIN
  ENCRYPTED PASSWORD 'md55149382dfba08d61605172830aae39d7'
  NOSUPERUSER INHERIT CREATEDB NOCREATEROLE NOREPLICATION;
CREATE DATABASE oaiserver
  WITH OWNER = oaiserver
       ENCODING = 'UTF8'
       TABLESPACE = pg_default       
       CONNECTION LIMIT = -1;
GRANT ALL ON DATABASE oaiserver TO oaiserver;
REVOKE ALL ON DATABASE oaiserver FROM public;  